trigger:
- main

pool:
  name: "Default"

steps:
- script: echo "Iniciando pipeline CI/CD"
  displayName: "Inicio del Pipeline"

# Paso 1: Construcción con Maven usando la tarea oficial de Azure DevOps
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: "Build con Maven"

# Paso 2: Ejecutar pruebas (ya incluidas en el build de Maven)

# Paso 3: Subir cambios a GitHub
- script: |
    git config --global user.email "ejemplo@email.com"
    git config --global user.name "TheChoyERROR"
    git remote add github https://github.com/TheChoyERROR/Azure001.git
    git push github main
  displayName: "Subir cambios a GitHub"
  env:
    GITHUB_TOKEN: $(DyelPYtaIFJHCOTydGHiXMhxSpeAOpyIeuK1503Rhr6ct6qovtzOJQQJ99BBACAAAAAAAAAAAAASAZDO3miF)
