trigger:
  - main

pool:
  name: "Default"

steps:
  - script: echo "🚀 Iniciando pipeline CI/CD"
    displayName: "Inicio del Pipeline"

  # Verificar que Maven está correctamente instalado
  - script: |
      echo "🔍 Verificando Maven..."
      mvn -version
    displayName: "Verificar Maven"

  # Construcción con Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
    displayName: "🔧 Build con Maven"

  # Subir cambios a GitHub (asegurar que el repositorio remoto existe)
  - script: |
      git config --global user.email "ejemplo@email.com"
      git config --global user.name "TheChoyERROR"
      git remote set-url origin https://$(GITHUB_TOKEN)@github.com/TheChoyERROR/Azure001.git
      git add .
      git commit -m "Actualización desde Azure DevOps"
      git push origin main
    displayName: "📤 Subir cambios a GitHub"
    env:
    GITHUB_TOKEN: $(DyelPYtaIFJHCOTydGHiXMhxSpeAOpyIeuK1503Rhr6ct6qovtzOJQQJ99BBACAAAAAAAAAAAAASAZDO3miF)
